# Generated by Django 2.2.1 on 2019-05-13 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_auto_20190513_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcategory',
            old_name='status',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='addpost',
            old_name='status',
            new_name='active',
        ),
        migrations.AddField(
            model_name='addcategory',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addpost',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
