# Generated by Django 2.2.1 on 2019-05-27 18:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
